# ${{ }} uses github context, ${} gets VM env

name: CI on pull_request and push to develop

on:
  # GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.
  pull_request:
    branches: [develop] # d. (opened, synchronize, or reopened)
  push:
    branches: [develop] #

env:
  DOCKER_USERNAME: jojoooo1

jobs:
  dump-info:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: set-env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_HEAD_REF # Only set for forked repositories. The branch of the head repository.
          echo $GITHUB_BASE_REF # Only set for forked repositories. The branch of the base repository.

          echo "$GITHUB_CONTEXT"

          echo "STEPS_ENV='VARIABLE_AVAILABLE_IN_STEPS'" >> $GITHUB_ENV
          echo '::set-output name=JOBS_ENV::VARIABLE_AVAILABLE_IN_JOBS'

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Dump matrix context
        run: |
          echo "STEPS_ENV: ${{ env.VARIABLE_AVAILABLE_IN_STEPS }}"
          echo "JOBS_ENV: ${{ jobs.dump-info.steps.set-env.outputs.JOBS_ENV }}"

      

  env_variable:
    runs-on: ubuntu-latest
    needs: [dump-info]
    # needs: dump-info
    # will triggered after pull request merge
    # if:  github.event_name == 'push' && contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@v2
      # Steps will be executed in order, if one fails following steps will not be executed
      # **ATTENTION** can not echo var in the same step $SOURCE_BRANCH_ENV will not return anything (can only be used in next step)
      - name: Sets ENV_VARIABLE
        run: |
          echo "SOURCE_BRANCH_ENV=${GITHUB_REF##*/}" >> $GITHUB_ENV
          # ONLY useful on: push
          

      - name: Sets OUTPUT_VAR
        id: branch_name
        run: |
          echo "SOURCE_BRANCH_OUTPUT=${GITHUB_REF##*/}" >> $GITHUB_ENV
          # ONLY useful on: push 

      - name: echo VAR
        run: |
          echo $SOURCE_BRANCH_ENV
          echo ${SOURCE_BRANCH_ENV}

          echo $SOURCE_BRANCH_OUTPUT
          echo $DOCKER_USERNAME

          echo ${{ env.SOURCE_BRANCH_OUTPUT }}
          echo ${{ env.DOCKER_USERNAME }}

          echo "JOBS_ENV: ${{ jobs.dump-info.steps.set-env.outputs.JOBS_ENV }}"

        env:
          SOURCE_BRANCH_OUTPUT: ${{ steps.branch_name.outputs.SOURCE_BRANCH_OUTPUT }}
        # echo ${ DOCKER_USERNAME }

      #
      #
      # GITHUB_TOKEN => will not create a new workflow run (to prevent recursive flow)
      # - name: Git force push
      #   run: |
      #     touch test.sh
      #     git config --global user.name ${{ github.actor }}
      #     git config --global user.email ${{ github.actor }}@users.noreply.github.com
      #     git add .
      #     git commit -m "force pushed [skip-ci]"
      #     echo "Pushing to ${{ steps.branch_name.outputs.SOURCE_BRANCH }}"
      #     git push --force origin ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
