# ${{ }} uses github context, ${} gets VM env

name: Testing

on:
  pull_request:
    branches: [master]
    
jobs:
  release_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Sets RELEASE_VERSION
        run: |
          RELEASE_VERSION=2.3.1
          TAG_LIST=(`echo $RELEASE_VERSION | tr '.' ' '`)
          if [[ "${#TAG_LIST[@]}" -ne 3 ]]; then
            echo "$RELEASE_VERSION is not a valid semantic version"
            exit 1
          else
            echo "VALID SEMANTIC_VERSION"
          fi
          # bug: not working
          # [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "$RELEASE_VERSION is not a valid semantic version" && exit 1
          #
          echo "CURLIIIIIIING"
          curl -X POST -u ${{ secrets.GITHUB_TOKEN }}:x-oauth-basic \
            --data '{"state": "success", "description": "Success!", "target_url": "test-url"}' \
            https://github.com/api/v3/repos/Jojoooo1/spring-boot-using-gitflow/statuses/$SHA_REF

          # curl -X POST "https://github.com/api/v3/repos/Jojoooo1/spring-boot-using-gitflow/statuses/$SHA_REF" \
          #   -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          #   -H 'Content-Type: application/json' \
          #   --data '{"state": "success", "context": "test-build-deploy-release-candidate"}'