# ${{ }} uses github context, ${} gets VM env

name: Testing

on:
  push:
    branches: [master]
    
jobs:
  release_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Sets RELEASE_VERSION
        run: |
          RELEASE_VERSION=2.3.1
          TAG_LIST=(`echo $RELEASE_VERSION | tr '.' ' '`)
          if [[ "${#TAG_LIST[@]}" -ne 3 ]]; then
            echo "$RELEASE_VERSION is not a valid semantic version"
            exit 1
          else
            echo "VALID SEMANTIC_VERSION"
          fi
          [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "$RELEASE_VERSION is not a valid semantic version" && exit 1